project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Página Inicial
      - text: Conteúdos
        menu:       
        - href: contents/nocoes_bascias.qmd
          text: Noções básicas
        - href: contents/otimizando.qmd
          text: Ferramentas auxiliares
        - href: contents/newcolumn.qmd
          text: Novas colunas  
        - href: contents/parbox.qmd
          text: Comando \parbox      
        - href: contents/notas.qmd
          text: Notas de rodapé
        - href: contents/longtables.qmd
          text: Longtables e ContinuedFloat          
        - href: contents/legenda.qmd
          text: Customização da legenda
        - href: contents/rotating.qmd
          text: Células rotacionadas e diagbox        
        - href: contents/quadro.qmd
          text: Quadros (ABNT) 
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    code-fold: false
    code-block-bg: true
    code-block-border-left: false
    code-line-numbers: false
    highlight-style: haddock